blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/rfestag/holoconf/discussions
    about: Ask questions and discuss ideas here
  - name: Documentation
    url: https://rfestag.github.io/holoconf/
    about: Check the docs first
